services:
  app:
    build: .
    container_name: app-python
    volumes:
      - .:/app
    ports:
      - "80:8000"
    networks:
      - class
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: python
    ports:
      - "5432:5432"
    networks:
      - class

networks:
  class:
    driver: bridge